### ISSUE TITLE
Hamburger menu improvements

### ISSUE THREAD

**Issue by RappyTV** [RappyBots/Boost-Frontend#8]
1. Add background
2. Center items
Otherwise it looks like this:
![image](https://github.com/RappyBots/Boost-Frontend/assets/72705182/2336dfc8-a8c0-4dd2-a441-7065ddeead30)

**Comment by holybaechu** [comment]
Looks like webkit issue. Chromium/Gecko based browsers on mobile works fine.

**Comment by holybaechu** [comment]
Does it work in [c725de7](https://github.com/RappyBots/Boost-Frontend/pull/3/commits/c725de794cf52c56602b9286de122fe980b07bd9)?

**Comment by RappyTV** [comment]
it does work but the items are not centered :)
